spring:
  datasource:
    url: jdbc:mysql://localhost:3306/badcomments?serverTimezone=UTC&characterEncoding=UTF-8
    username: badcomments_user
    password: 비밀번호
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
